spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application:
    name: APIProxy
  cloud:
    loadbalancer:
      enabled: true
      health-check:
        refetch-instances-interval: 5s
        refetch-instances: true
      cache:
        enabled: false
      retry:
        avoid-previous-instance: true
    gateway:
      httpserver:
        wiretap: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: GatewayStarship
          uri: lb://GatewayStarship
          predicates:
            - Path=/**
            - Method=GET, POST, PUT, DELETE, OPTIONS
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:8080"
            allowedHeaders: "*"
            allowedMethods: "*"

logging:
  level:
    org.springframework.cloud.loadbalancer: INFO
    reactor: INFO
    org.springframework.cloud.gateway: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:10100}/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
  instance:
    hostname: ${EUREKA_HOST:localhost}

server:
  port: 10200